CREATE TABLE configurations (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(100) NOT NULL,
    "Value" character varying(1000) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Category" character varying(50) NOT NULL,
    "IsSecret" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    "UpdatedBy" character varying(100) NOT NULL,
    CONSTRAINT "PK_configurations" PRIMARY KEY ("Id")
);


CREATE TABLE failures (
    "Id" uuid NOT NULL,
    "FailureNumber" character varying(50) NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    "Severity" text NOT NULL,
    "Status" text NOT NULL,
    "Activity" text,
    "OccurredAt" timestamp with time zone NOT NULL,
    "Environment" text,
    "UserStoryId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    CONSTRAINT "PK_failures" PRIMARY KEY ("Id")
);


CREATE TABLE issues (
    "Id" uuid NOT NULL,
    "IssueNumber" character varying(50) NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    "Type" text NOT NULL,
    "Priority" text NOT NULL,
    "Status" text NOT NULL,
    "Activity" character varying(100),
    "Environment" text,
    "UserStoryId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    CONSTRAINT "PK_issues" PRIMARY KEY ("Id")
);


CREATE TABLE logs (
    "Id" uuid NOT NULL,
    "Action" character varying(100) NOT NULL,
    "Entity" character varying(100) NOT NULL,
    "EntityId" character varying(100),
    "UserId" character varying(100) NOT NULL,
    "Details" character varying(500),
    "Level" text NOT NULL,
    "IpAddress" character varying(50),
    "UserAgent" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" character varying(100) NOT NULL,
    "UpdatedBy" character varying(100),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_logs" PRIMARY KEY ("Id")
);


CREATE TABLE profiles (
    "Id" uuid NOT NULL,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(200),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" character varying(100) NOT NULL,
    "UpdatedBy" character varying(100),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_profiles" PRIMARY KEY ("Id")
);


CREATE TABLE user_stories (
    "Id" uuid NOT NULL,
    "DemandNumber" character varying(50) NOT NULL,
    "Title" character varying(255) NOT NULL,
    "AcceptanceCriteria" text NOT NULL,
    "Description" text,
    "Status" text NOT NULL,
    "Priority" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" character varying(100) NOT NULL,
    CONSTRAINT "PK_user_stories" PRIMARY KEY ("Id")
);


CREATE TABLE users (
    "Id" uuid NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Nickname" character varying(50) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "ProfileImagePath" character varying(500),
    "ProfileId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" character varying(100) NOT NULL,
    "UpdatedBy" character varying(100),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_users_profiles_ProfileId" FOREIGN KEY ("ProfileId") REFERENCES profiles ("Id") ON DELETE RESTRICT
);


CREATE TABLE attachments (
    "Id" uuid NOT NULL,
    "FileName" character varying(255) NOT NULL,
    "OriginalFileName" character varying(255) NOT NULL,
    "ContentType" character varying(100) NOT NULL,
    "Size" bigint NOT NULL,
    "FilePath" text NOT NULL,
    "UserStoryId" uuid,
    "IssueId" uuid,
    "FailureId" uuid,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" character varying(100) NOT NULL,
    "UpdatedBy" character varying(100),
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_attachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_attachments_failures_FailureId" FOREIGN KEY ("FailureId") REFERENCES failures ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_attachments_issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES issues ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_attachments_user_stories_UserStoryId" FOREIGN KEY ("UserStoryId") REFERENCES user_stories ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_attachments_FailureId" ON attachments ("FailureId");


CREATE INDEX "IX_attachments_IssueId" ON attachments ("IssueId");


CREATE INDEX "IX_attachments_UserStoryId" ON attachments ("UserStoryId");


CREATE INDEX "IX_configurations_Category" ON configurations ("Category");


CREATE INDEX "IX_configurations_CreatedAt" ON configurations ("CreatedAt");


CREATE INDEX "IX_configurations_IsActive" ON configurations ("IsActive");


CREATE UNIQUE INDEX "IX_configurations_Key" ON configurations ("Key");


CREATE INDEX "IX_failures_FailureNumber" ON failures ("FailureNumber");


CREATE INDEX "IX_failures_OccurredAt" ON failures ("OccurredAt");


CREATE INDEX "IX_failures_Severity" ON failures ("Severity");


CREATE INDEX "IX_failures_Status" ON failures ("Status");


CREATE INDEX "IX_issues_IssueNumber" ON issues ("IssueNumber");


CREATE INDEX "IX_issues_Priority" ON issues ("Priority");


CREATE INDEX "IX_issues_Status" ON issues ("Status");


CREATE INDEX "IX_issues_Type" ON issues ("Type");


CREATE INDEX "IX_logs_CreatedAt" ON logs ("CreatedAt");


CREATE INDEX "IX_logs_Entity" ON logs ("Entity");


CREATE INDEX "IX_logs_Level" ON logs ("Level");


CREATE INDEX "IX_logs_UserId" ON logs ("UserId");


CREATE INDEX "IX_profiles_CreatedAt" ON profiles ("CreatedAt");


CREATE INDEX "IX_profiles_IsActive" ON profiles ("IsActive");


CREATE UNIQUE INDEX "IX_profiles_Name" ON profiles ("Name");


CREATE INDEX "IX_user_stories_CreatedAt" ON user_stories ("CreatedAt");


CREATE INDEX "IX_user_stories_DemandNumber" ON user_stories ("DemandNumber");


CREATE INDEX "IX_user_stories_Priority" ON user_stories ("Priority");


CREATE INDEX "IX_user_stories_Status" ON user_stories ("Status");


CREATE INDEX "IX_users_CreatedAt" ON users ("CreatedAt");


CREATE UNIQUE INDEX "IX_users_Email" ON users ("Email");


CREATE INDEX "IX_users_IsActive" ON users ("IsActive");


CREATE UNIQUE INDEX "IX_users_Nickname" ON users ("Nickname");


CREATE INDEX "IX_users_ProfileId" ON users ("ProfileId");


