@IntegrationAzure.Api_HostAddress = http://localhost:5066

### Login com credenciais válidas
POST {{IntegrationAzure.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "123456"
}

### Login com credenciais inválidas
POST {{IntegrationAzure.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "senha123"
}

### Validar sessão
GET {{IntegrationAzure.Api_HostAddress}}/api/auth/validate
Accept: application/json

### Logout
POST {{IntegrationAzure.Api_HostAddress}}/api/auth/logout
Content-Type: application/json
